### ISSUE TITLE
SFDC Digital Engagement Data in SFMC

### ISSUE THREAD

**Issue by dheerajkottali** [cncf/sfdc#10]
Hi,

I require digital engagement data in SFMC. This data consists of done webinars and blogs to be displayed in the quarterly email.

**Comment by dankohn** [comment]
Can you please add some detail.

**Comment by dheerajkottali** [comment]
Requirement is to display the list of webinars and blogs that are done with CNCF over the last 3 months.
For this to show on the email, we need to get the "Digital Engagement" custom object data from SFDC to SFMC through synchronized data extensions. 
SFMC administrator needs to create a synchronized data extension in SFMC and pull the data from "Digital Engagement" custom object data. This data consists of blogs and webinars that are done for Accounts.

**Comment by dankohn** [comment]
Sounds good. @kwussow please open a Jira ticket, assign to Marijana, share with me, and paste the URL here. Separately, please open a separate Jira ticket to get @dheerajkottali access to LF Jira.

**Comment by kwussow** [comment]
@dankohn I opened a Jira ticket here: https://jira.linuxfoundation.org/browse/LP-5826?workflowName=Workflow+creative+process&stepId=4
I will open a ticket to get Dheeraj access to LF Jira as well. Here is the link https://jira.linuxfoundation.org/servicedesk/customer/portal/3/LFIT-747

**Comment by KimMcMahon** [comment]
Hello @dheerajkottali. I have been uploading the webinar contacts to Salesforce. I'm about 2/3 complete. I'll finish uploading the recent webinars this week.

When I create the SF list, I add the company name to the "webinar" field. I may need to update the company name to ensure it correctly loads into the work you are doing. Can you review and let me know?

**Comment by kwussow** [comment]
@KimMcMahon Let's review today if you have time. We need to log the webinars in the "digital engagement" section in SFDC which is manual and a separate step from loading the lists into campaigns. Also, the issue of getting the fields to display in SFMC for Dheeraj has been fixed.
