### ISSUE TITLE
Add primary and alternate events contacts

### ISSUE THREAD

**Issue by dankohn** [cncf/sfdc#3]
We need fields showing the primary and alternate event contacts for every member.

**Comment by kwussow** [comment]
Primary event contact field created in the membership records in SFDC by Marijana's team. Currently, in the process due to Kathy not having appropriate access in SFDC to add the contacts. Katelin to check with Pallavi and Marijana on how to grant Kathy access to membership profiles in SFDC.

**Comment by kwussow** [comment]
Event Sponsorship contacts added for CNCF Platinum and Gold members here: https://linuxfoundation.lightning.force.com/lightning/r/Report/00O2M000009Jn8yUAC/view?queryScope=userFolders. 

Engagement email will include field requesting that our Silver members provide us with a contact.

**Comment by kwussow** [comment]
event sponsorship contact field exists in SFDC and we are collecting Silver members over time with engagement email.
