### ISSUE TITLE
Sponsorship dashboard showing all CNCF events % to revenue goal + sales stage with revenue

### ISSUE THREAD

**Issue by dankohn** [cncf/sfdc#6]

**Comment by kwussow** [comment]
The current dashboard in SFDC is [here] https://linuxfoundation.lightning.force.com/lightning/r/Dashboard/01Z2M0000019gJXUAY/view?queryScope=userFolders. Press refresh to see the current view.

Katelin is interviewing contractors to complete the following next steps:

- [ ] See if we can integrate the % to revenue goal report and number into the same box as the sponsorship forecast funnel. Can it be a text box under the title that shows the % to goal number as well as the revenue amount closed/won?

- [x] Can the funnels be created so they are all the same color for each forecast status? eg. closed/won remains dark blue in every funnel per event?

- [x] Have all numbers auto-refresh? No manual entry for this dashboard. Auto-update to remove reporting on an event that is closed aka: event end date is greater than the present day. 

- [ ] Create a new dashboard for 2020 events.


- [ ] Validate the numbers are accurate with Kathy

**Comment by kwussow** [comment]
Hi @dheerajkottali, here are all of the 2020 event names that need to be in the 2020 dashboard:

Kubernetes Forum Bengaluru 2020
Kubernetes Forum Delhi 2020
KubeCon + CloudNativeCon Europe 2020
Cloud Native Security Day Europe 2020
Serverless Practitioners Summit Europe 2020
ServiceMeshCon Europe 2020
gRPConf2020
KubeCon + CloudNativeCon + Open Source Summit China 2020
KubeCon + CloudNativeCon North America 2020

**Comment by dankohn** [comment]
And Kubernetes Forum Tokyo 2020

**Comment by kwussow** [comment]
Cannot integrate the % to revenue goal number into the same box as the sponsorship forecast funnel in SFDC natively, so Dheeraj is researching if/how we can do this with Einstein.

**Comment by kwussow** [comment]
@dankohn Are you ok with this order of events in the dashboard so they are in order of start date throughout the year? 
Kubernetes Forum Bengaluru 2020
Kubernetes Forum Delhi 2020
KubeCon + CloudNativeCon Europe 2020
Cloud Native Security Day Europe 2020
Serverless Practitioners Summit Europe 2020
ServiceMeshCon Europe 2020
gRPConf2020
KubeCon + CloudNativeCon + Open Source Summit China 2020
KubeCon + CloudNativeCon North America 2020

Or would you prefer them grouped by event type, so KubeCon events first, Project events second, Kubernetes Forms last?
Thanks!

**Comment by kwussow** [comment]
@dheerajkottali is working with Pallavi to get the production data into the sandbox. We are still missing K8s Delhi and Bengaluru data in sandbox.

**Comment by dankohn** [comment]
By event date is my preference.

**Comment by kwussow** [comment]
@dankohn Please find updated CNCF Event sponsorship dashboard here: https://linuxfoundation.lightning.force.com/wave/wave.app?tsid=02u2M000001Z7xA#dashboard/0FK2M000000bpIHWAY for your review. I also have a call with the rest of the sponsorship sales team + Colleen this Thursday to share and get feedback.

**Comment by kwussow** [comment]
This dashboard is complete for 2020.
